In [6]:
import numpy as np

In [7]:
data = [4,5,6,7]
a = np.array(data)

In [8]:
a

array([4, 5, 6, 7])

In [9]:
a.ndim

1

In [10]:
print(a.size)

4


In [11]:
a*2

array([ 8, 10, 12, 14])

In [12]:
a**3

array([ 64, 125, 216, 343], dtype=int32)

In [13]:
#indexing
a[0]

4

In [14]:
a[-1]

7

In [15]:
a

array([4, 5, 6, 7])

In [16]:
#slicing
a[1:3] #start:stop 

array([5, 6])

In [17]:
a[0:3:2] #Start:Stop:step

array([4, 6])

In [18]:
a[:]

array([4, 5, 6, 7])

In [19]:
a[:3]

array([4, 5, 6])

In [20]:
a[1:]

array([5, 6, 7])

In [21]:
####### 2-D array #######

In [22]:
d = [[1,2,3],[4,5,6],[7,8,9]]
s = np.array(d)

In [23]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
s.ndim

2

In [25]:
s.shape

(3, 3)

In [26]:
s.size

9

In [27]:
#Indexing
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
s[0]

array([1, 2, 3])

In [29]:
s[:2,1:]

array([[2, 3],
       [5, 6]])

In [30]:
s[:,0]#selects all the rows but first column

array([1, 4, 7])

In [31]:
s[1:,:] #gives last two rows

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
s[1:,1:]

array([[5, 6],
       [8, 9]])

In [33]:
#arange()


In [34]:
d = np.arange(1,10,2) #start,stop,step
d

array([1, 3, 5, 7, 9])

In [35]:
d =np.arange(9)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
#reshaping arrays
k = d.reshape(9,1) #rows,columns
k

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [37]:
k = d.reshape(3,3) #rows,columns
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
k = d.reshape(2,3) #rows,columns
k

In [39]:
k.shape

(3, 3)

In [40]:
#making 2D array through arange()
x = np.arange(10,19).reshape(3,3) 
x

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [41]:
x[1:,:2]

array([[13, 14],
       [16, 17]])

## Concatenation of 2 arrays

In [42]:
x= np.array ([[1,2],[3,4]])
y= np.array ([[5,6],[7,8]])
x

array([[1, 2],
       [3, 4]])

In [43]:
y

array([[5, 6],
       [7, 8]])

In [44]:
s = np.concatenate((x,y), axis=1) #columnwise
s

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [45]:
s.shape

(2, 4)

In [46]:
s = np.concatenate((x,y), axis=0) #row-wise
s

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
s.shape

(4, 2)

In [48]:
s.transpose()

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [49]:
s

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Matrix Multiplication

In [50]:
x

array([[1, 2],
       [3, 4]])

In [51]:
y

array([[5, 6],
       [7, 8]])

In [52]:
z = np.matmul(x,y)
z

array([[19, 22],
       [43, 50]])

In [53]:
z.shape

(2, 2)

In [54]:
x = np.arange(1,13).reshape(4,3)
y = np.arange (1,13).reshape(4,3)

In [55]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
z = np.matmul(x,y)

In [58]:
z = np.matmul(x,y.transpose())

In [59]:
z

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266],
       [ 68, 167, 266, 365]])

In [60]:
#### Unique Values
z= np.array([1,2,3,3,2,4,6,7,8,3,8,6])


In [61]:
np.unique(z)

array([1, 2, 3, 4, 6, 7, 8])

In [62]:
np.unique(z,return_counts=True)

(array([1, 2, 3, 4, 6, 7, 8]), array([1, 2, 3, 1, 2, 1, 2], dtype=int64))

In [63]:
np.bincount(z)

array([0, 1, 2, 3, 1, 0, 2, 1, 2], dtype=int64)

In [64]:
## Convert 2d array to 1d array
s

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
x= s.flatten()
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
x[x>5]

array([6, 7, 8])

In [67]:
z = np.arange(11,21)
z

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
indexes = np.where(z>17) #gives indexes of satistisfied numbers
indexes

(array([7, 8, 9], dtype=int64),)

In [69]:
z[indexes]

array([18, 19, 20])

In [70]:
d = np.arange(11,20).reshape(3,3)
d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [71]:
q = np.where(z>13)
q

(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [72]:
x= np.array ([[1,2],[5,6]])
y= np.array ([[7,8],[9,10]])
x

array([[1, 2],
       [5, 6]])

In [73]:
y

array([[ 7,  8],
       [ 9, 10]])

In [74]:
np.vstack((x,y)) #Vertical stacking --- other way of concatenation


array([[ 1,  2],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [75]:
np.hstack((x,y)) #horizontal stacking

array([[ 1,  2,  7,  8],
       [ 5,  6,  9, 10]])

In [76]:
np.mean(x)

3.5

In [77]:
np.median(x)

3.5

In [78]:
##Generate random values

In [79]:
np.random.randint(1,10,(3,4)) #start,stop,shape  # for random int vaues

array([[3, 5, 2, 2],
       [5, 7, 6, 1],
       [4, 3, 7, 1]])

In [80]:
np.random.rand(2,3)  # for random float vaues only b/w 0 & 1

array([[0.56331941, 0.90756447, 0.16408723],
       [0.65223868, 0.96090818, 0.73674114]])

In [81]:
np.random.uniform(-5,5,(3,3))  # for random float vaues b/w given conditions

array([[ 2.02793976,  4.47365383,  2.48845491],
       [ 1.07233276, -3.38959674, -0.26534908],
       [ 4.56703126,  3.26638498,  0.82327325]])

In [82]:
m = np.linspace(0,1,5) # gives values with equal spaces
m

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [83]:
np.random.shuffle(m)
m

array([0.25, 0.5 , 0.  , 1.  , 0.75])

In [84]:
y

array([[ 7,  8],
       [ 9, 10]])

In [85]:
y.max()

10

In [86]:
y.argmax() # get index of max value

3

In [87]:
y.min()

7

In [88]:
y.argmin() # get index of min value

0